import type { Channel, Stream, Category, ChatMessage } from "../types";

export const followedChannels: Channel[] = [
  {
    id: 1,
    name: "xQcOW",
    game: "Valorant",
    viewers: 45231,
    live: true,
    initials: "XQ",
    color: "#E74C3C",
  },
  {
    id: 2,
    name: "HasanAbi",
    game: "Just Chatting",
    viewers: 52100,
    live: true,
    initials: "HA",
    color: "#9B59B6",
  },
  {
    id: 3,
    name: "Hikaru",
    game: "Chess",
    viewers: 18442,
    live: true,
    initials: "HK",
    color: "#3498DB",
  },
  {
    id: 4,
    name: "Nickmercs",
    game: "Warzone",
    viewers: 31000,
    live: true,
    initials: "NK",
    color: "#F39C12",
  },
  {
    id: 5,
    name: "Trainwrecks",
    game: "Slots",
    viewers: 28910,
    live: true,
    initials: "TW",
    color: "#E67E22",
  },
  {
    id: 6,
    name: "Summit1g",
    game: "VALORANT",
    viewers: 22000,
    live: true,
    initials: "S1",
    color: "#1ABC9C",
  },
  {
    id: 7,
    name: "Symfuhny",
    game: "Fortnite",
    viewers: 12500,
    live: false,
    initials: "SF",
    color: "#8E44AD",
  },
  {
    id: 8,
    name: "Sneaky",
    game: "League of Legends",
    viewers: 8320,
    live: false,
    initials: "SN",
    color: "#27AE60",
  },
];

export const streams: Stream[] = [
  {
    id: 1,
    title: "RANKED GRIND — Road to Diamond | 10h stream !prime",
    streamer: "xQcOW",
    game: "Valorant",
    viewers: 45231,
    thumbnail: "photo-1542751371-adc38448a05e",
    tags: ["English", "FPS", "Competitive"],
    initials: "XQ",
    color: "#E74C3C",
    featured: true,
  },
  {
    id: 2,
    title: "Morning grind - 2000 ELO or we go again",
    streamer: "Hikaru",
    game: "Chess",
    viewers: 18442,
    thumbnail: "photo-1523875194681-bedd468c58bf",
    tags: ["English", "Chess"],
    initials: "HK",
    color: "#3498DB",
    featured: false,
  },
  {
    id: 3,
    title: "WARZONE SOLOS — NEW META LOADOUT NO CAP",
    streamer: "Nickmercs",
    game: "Warzone",
    viewers: 31000,
    thumbnail: "photo-1560253023-3ec5d502959f",
    tags: ["English", "FPS"],
    initials: "NK",
    color: "#F39C12",
    featured: false,
  },
  {
    id: 4,
    title: "Just chatting with the Hasan gang — politics & gaming",
    streamer: "HasanAbi",
    game: "Just Chatting",
    viewers: 52100,
    thumbnail: "photo-1593305841991-05c297ba4575",
    tags: ["English", "IRL"],
    initials: "HA",
    color: "#9B59B6",
    featured: false,
  },
  {
    id: 5,
    title: "Summit plays: STALKER 2 first playthrough",
    streamer: "Summit1g",
    game: "STALKER 2",
    viewers: 22000,
    thumbnail: "photo-1511512578047-dfb367046420",
    tags: ["English", "Horror"],
    initials: "S1",
    color: "#1ABC9C",
    featured: false,
  },
  {
    id: 6,
    title: "Pro scrims | Fnatic bootcamp - EU championship prep",
    streamer: "Symfuhny",
    game: "Fortnite",
    viewers: 12500,
    thumbnail: "photo-1580327344181-c1163234e5a0",
    tags: ["English", "Tournament"],
    initials: "SF",
    color: "#8E44AD",
    featured: false,
  },
];

export const categories: Category[] = [
  { name: "Valorant", viewers: 312000, img: "photo-1542751371-adc38448a05e" },
  {
    name: "Fortnite",
    viewers: 248000,
    img: "photo-1580327344181-c1163234e5a0",
  },
  {
    name: "Just Chatting",
    viewers: 198000,
    img: "photo-1593305841991-05c297ba4575",
  },
  { name: "Chess", viewers: 87000, img: "photo-1560174038-da43ac74f01b" },
];

export const messages: ChatMessage[] = [
  {
    user: "GreenTurtle99",
    msg: "LET'S GOOO he just clutched that 1v4!",
    color: "#27AE60",
  },
  {
    user: "NightOwlAce",
    msg: "bro is actually cracked fr fr",
    color: "#3498DB",
  },
  {
    user: "ProGamerXD",
    msg: "what sens is he on??",
    color: "#9B59B6",
  },
  {
    user: "CryptoKing",
    msg: "KEKW that was clean",
    color: "#F39C12",
  },
  {
    user: "ShadowByte",
    msg: "he's going to hit radiant by next week I'm calling it",
    color: "#E74C3C",
  },
  {
    user: "VoidWalker",
    msg: "insane movement no cap",
    color: "#1ABC9C",
  },
  {
    user: "GreenTurtle99",
    msg: "pog pog pog",
    color: "#27AE60",
  },
  {
    user: "ArcadePhoenix",
    msg: "can't stop watching this stream 😭",
    color: "#E67E22",
  },
];
